<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Company;
use AppBundle\Entity\Search;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{
    /**
     * @param Search $search
     *
     * @return Company[]
     */
    public function fetchAllFromSearch(Search $search)
    {
        $qb = $this->createQueryBuilder('c');
        
        $qb
            ->join('c.collaborators', 'co')
            ->join('co.inSearches', 'sd')
            ->join('sd.search', 's')
            ->where($qb->expr()->eq('s', ':search'))
            ->setParameter('search', $search)
        ;
        
        return $qb->getQuery()->getResult();
    }
    
    /**
     * @param User $user
     *
     * @return Company[]
     */
    public function fetchAllFromUser(User $user)
    {
        $qb = $this->createQueryBuilder('c');
        
        $qb
            ->join('c.collaborators', 'co')
            ->join('co.inSearches', 'sd')
            ->join('sd.search', 's')
            ->join('s.owner', 'o')
            ->where($qb->expr()->eq('o', ':owner'))
            ->setParameter('owner', $user)
        ;
        
        return $qb->getQuery()->getResult();
    }
}
