<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Company;
use AppBundle\Entity\Search;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{
    public function fetchGroupedForDashboard(Search $search)
    {
        $qb = $this->createQueryBuilder('c');
        
        $qb
            ->select('c as company')
            ->addSelect('COUNT(c.id) as count_search_details')
            ->leftJoin('c.searchDetails', 'sd')
            ->leftJoin('sd.search', 's')
            ->andWhere($qb->expr()->eq('s', ':search'))
            ->setParameter('search', $search)
            ->groupBy('c.id')
            ->orderBy('sd.createdAt')
        ;
        
        return $qb->getQuery()->getResult();
    }
}
