services:
    app.form.company:
        class: AppBundle\Form\CompanyType
        arguments:
            - "@security.authorization_checker"
        tags:
            - { name: form.type }

    app.form.company.collaborator:
        class: AppBundle\Form\Company\CollaboratorType
        arguments:
            - "@security.token_storage"
        tags:
            - { name: form.type }
