services:
    app.subscriber.company:
        class: AppBundle\Subscriber\Doctrine\AddCurrentUser
        arguments: ["@security.token_storage"]
        tags:
            - { name: doctrine.event_listener, event: prePersist }

