services:
    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }

    twig.extension.date:
       class: Twig_Extensions_Extension_Date
       arguments: ["@translator"]
       tags:
           - { name: twig.extension }

    app.twig.country_extension:
        class: AppBundle\Twig\CountryExtension
        public: false
        tags:
            - { name: twig.extension }

    app.twig.markdown_extension:
            class:     AppBundle\Twig\MarkdownExtension
            arguments: ['@app.utils.markdown']
            public:    false
            tags:
                - { name: twig.extension }
