services:
    app.twig.country_extension:
        class: AppBundle\Twig\CountryExtension
        public: false
        tags:
            - { name: twig.extension }

    app.twig.markdown_extension:
            class:     AppBundle\Twig\MarkdownExtension
            arguments: ['@app.utils.markdown']
            public:    false
            tags:
                - { name: twig.extension }
